title: Bridgit Nguyen
logo: /assets/img/logo.png
description: B.S. Mechanical Engineering 26â€™ at University of Rochester
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
